### ISSUE TITLE
Add missing fields

### ISSUE THREAD

**Issue by famoser** [famoser/egoi-registration#1]
The following fields are missing:
- `Immigration`: `immigrationAssisstanceRequired` (bool)
- `PersonalData`: `parentalConsent` (file)

**Comment by cneukom** [comment]
- The field `Contributions` -> `Translations` should be structured, so that scripts can automatically process that information from the data export, i.e. ISO 639-1 codes would be reasonable.
- There should be the possibility to admit delegations only for online participation, i.e. these countries should not be able to change the field to onsite themselves.
- `Personal Data` -> `Gender` should be pre-filled with `female`, not `woman`.

**Comment by famoser** [comment]
`There should be the possibility to admit delegations only for online participation, i.e. these countries should not be able to change the field to onsite themselves.` -> can this be a `nice to have`? With the review process, the organizer has full control what is "approved" in the end, and hence can easily enforce this.
